### ISSUE TITLE
Database: make button more prominent and easy to find

### ISSUE THREAD

**Issue by roalyr** [biqqles/wingman#4]

**Comment by biqqles** [comment]
This is a good idea. I honestly didn't expect people to be as interested in Database as they apparently are - I mainly wrote it to validate my parsing library! As far as the UI goes, the only real option is to add its action directly to the menubar rather than it being in a submenu. However when I tried doing that just now it didn't show up. I'm not sure if this an issue with KDE's global menu (which I use) or is generally a problem.

**Comment by biqqles** [comment]
(Just copying this information in from Discord.)

I did manage to implement this, and it looks like this in Windows:

![image](https://user-images.githubusercontent.com/19939282/97085870-01ca6680-1618-11eb-9875-fa5fd4178059.png)

The code is in the referenced commit.

However, it doesn't work with KDE's global menu (the action does not show up) which is somewhat expected since adding an action directly to a menu bar is quite unusual. If this can't be worked around, it will remain only as an experiment.

**Comment by biqqles** [comment]
![image](https://user-images.githubusercontent.com/19939282/99579706-748bef00-29d6-11eb-89a6-6d540b28a80c.png)
Added in 228042c.
